---
title: "Frequency Tables"
format: live-html
engine: knitr
---
```{webr}
#| context: setup
#| autorun: false
#| message: false
#| warning: false
download.file(
  "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv",
  "titanic.csv"
)
library(tidyverse)
library(ggplot2)
df <- read_csv("titanic.csv")
```

# Frequency Tables 
We can make a data visualization called a  **Frequency Table** with the count() function. 
The input for count() is the name of the column you want to get the value counts of. For example, we know that the `Survived` column in our dataset tells us whether or not a passenger survived, where a 0 means they did not survive, and a 1 means they did survive. 
We want to know how many 0s and 1s there are in total. 

```{webr}
#| autorun: false
df %>% count(Survived)
```

## Improving Readability 
The output of count() alone is ugly and hard to read. 
```{webr}
#| autorun: false 
df %>% count(Survived, name = "Count")
```

Just '0s' and '1s' is also not informative. We can rename the values as well. 
```{webr}
#| autorun: false 
df %>%
  mutate(Survived = if_else(Survived == 1, "Survived", "Died")) %>%
  count(Survived, name = "Count")
```


## Add proportions 
We can also make show *relative* frequency instead of *absolute* frequency by showing proportions instead of raw counts. 
```{webr}
df %>%
  count(Survived, name = "Count") %>%
  mutate(Percent = round(100 * Count / sum(Count), 1))
```

### There are many other ways to make your visuals easier to read and/or aesthetically pleasing. 
```{webr}
df %>%
  mutate(Survived = if_else(Survived == 1, "Survived", "Died")) %>%
  count(Survived, name = "Count") %>%
  mutate(Proportion = round(Count / sum(Count), 3)) %>%
  knitr::kable()
```

Now we can tell at a glance, how deadly the Titanic disaster was. 




