---
title: "Linear Regression"
format: 
  live-html: 
    code-fold: true
    code-summary: "Show code"
engine: knitr
---
We found a strong positive correlation between prison population and violent crime, but this does not license any claims about the *size* of correlation between prison population and violent crimes. For this we need to run a linear regression. 

# Linear Regression Recap 
1. In a linear regression, we make Y depend on X: 
2. This is called a linear function because it produces a straight line between X and Y
- This is the same as the formula we learn in algebra: y = mx + b, the letters are just different. 
3. The output of this function is the expected value of Y, after we input any value of X.  
4. In our cases, we have observed values of X and Y, and we want to find out what alpha and beta are.
5. Recall that ater plotting our data on a scatterplot, we calculate $r$ -- how closely the relationship between x and y follows a linear trend. 
6. In a linear regression, we're drawing that line -- **the line of best fit** on our scatterplot, and figuring out $\alpha$ and $\beta$ from that line. 

This is useful, because $\beta$ *is* the size of the relationship between X and Y. 

# Plotting line of best fit
```{webr}
#| context: setup
#| message: false
#| warning: false
download.file(
  "https://raw.githubusercontent.com/emzou/r-guide/main/r-code/visuals/prison.csv",
  "prison.csv"
)
library(tidyverse)
library(ggplot2)
```

```{webr}
#| autorun: false
df <- read_csv("prison.csv", show_col_types = FALSE)
```

## geom_smooth

```{webr}
#| autorun: false
ggplot(df, aes(x = pris, y = criv)) +
  geom_point() +
  geom_smooth()
```

# Estimating coefficients 
We have our line after plotting with geom_smooth, and we can estimate the actual formula for the line with the `lm()` function. 

```{webr}
#| autorun: false
lm(df$criv ~ df$pris)
```

The actual output you want to look at is with the summmary() function 
```{webr}
#| autorun: false
ols.reg <- lm(df$criv ~ df$pris)
summary(ols.reg)
```

Look for the "Coefficients" section, where the Intercept and dependent variable will be shown in a table with its Estimate, Std. Error, t value, and Pr(>|t|). 
The estimates are the linear regression's best guesses for the value of $\alpha$ and $\beta$. 

Plugging it into the formula for a line, our model is y = 2.012x + 105.459. Because the estimates aren't the actual value -- they're just a guess -- the estimate for $\alpha$ is referred to as $\hat{\alpha}$ , and $\beta$ as $\hat{\beta}$ . 

(Out loud, people typically say alpha hat and beta hat :^) 

## Interpretation 
### Generally 

1. $\hat{\alpha}$ is the intercept on the y-axis, the value that Y takes when X is zero. $\hat{\alpha}$ is a constant, it doesn't change and remains the same regardless of the value of X. 
2. $\hat{\beta}$ is the coefficient (or slope), the average change in Y for one unit increase in X. $\hat{\beta}$ is always in terms of Y's units. 

To report your results, you can say something like: "On average, Y changes by $\hat{\beta}$ [Y's units] for a 1 [X's unit] increase in X."


### Translated in this case 
"Each additional prisoner per 100,000 people in the previous year is associated with an increase of 2.012 in the predicted violent crime rate per 100,000 people."