project:
  type: website
  output-dir: _site

website:
  title: "R basics"
  site-url: "https://emzou.github.io/r-guide/"
  repo-url: "https://github.com/emzou/r-guide"
  repo-actions: [edit, issue]

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: r-setup/index.qmd
        text: "R Setup"
      - href: r-code/index.qmd
        text: "R Code"

    right:
      - icon: github
        href: "https://github.com/emzou/r-guide"

  sidebar:
    - id: r-setup
      title: "R Setup"
      style: docked
      collapse-level: 1
      contents:
        - r-setup/index.qmd
        - section: "1. Install R"
          contents:
            - auto: "r-setup/install-r/*.qmd"
        - section: "2. Install RStudio"
          contents:
            - auto: "r-setup/install-rstudio/*.qmd"
        
    - id: r-code
      title: "Workflow Organization"
      style: docked
      collapse-level: 1
      contents:
        - r-code/index.qmd
        - auto: "r-code/0*.qmd"

    

  page-footer:
    left: "Last built {{< meta date >}}"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: litera
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap

date: today
date-format: "MMM D, YYYY"

language:
  title-block-published: "Last updated"

execute:
  freeze: auto