project:
  type: website
  output-dir: _site

website:
  title: "R(eference)"
  page-navigation: true
  favicon: favicon.png
  site-url: "https://emzou.github.io/r-guide/"
  repo-url: "https://github.com/emzou/r-guide"
  repo-actions: [edit, issue]

  sidebar:
    style: docked
    search: true
    collapse-level: 1
    tools:
      - icon: home
        href: "https://github.com/emzou/r-guide"
    contents:
      - href: index.qmd
        text: Home

      - section: "R Setup"
        href: r-setup/index.qmd
        contents:
          - section: "Install R"
            contents:
              - auto: "r-setup/install-r/*.qmd"
          - section: "Install RStudio"
            contents:
              - auto: "r-setup/install-rstudio/*.qmd"
          - section: "Make R Markdown File"
            contents:
              - auto: "r-setup/make-rmd/*.qmd"
          - section: "Loading in data"
            contents:
              - auto: "r-setup/load-data/*.qmd"
          - section: "Working Directory"
            contents:
              - auto: "r-setup/check-wd/*.qmd"

      - section: "Data Manipulation"
        href: r-code/index.qmd
        contents:
          - section: "Classes and Functions"
            contents:
              - auto: "r-code/first/*.qmd"
          - section: "Dataframes"
            contents:
              - auto: "r-code/load_data/*.qmd"
          
      - section: "Description of One Variable"
        href: descrip-stat/index.qmd
        contents:
          - auto: "descrip-stat/*.qmd"

      - section: "Comparisons between Two Variables"
        href: comparisons/index.qmd
        contents:
          - section: "Cross Tabluation"
            contents:
              - auto: "comparisons/crosstab/*.qmd"
          - section: "Comparison of Means"
            contents:
              - auto: "comparisons/compmeans/*.qmd"
          - section: "Hypothesis Testing"
            contents:
              - auto: "comparisons/hypotest/*.qmd"
          - section: "Correlation"
            contents:
              - auto: "comparisons/correlation/*.qmd"
          - section: "Regressions"
            contents:
              - auto: "comparisons/regression/*.qmd"
         

    

  page-footer:
    left: "Last built {{< meta date >}}"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: litera
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
  live-html: 
    theme: litera
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap

webr:
  packages: ['ggplot2', 'tidyverse']

date: today
date-format: "MMM D, YYYY"

language:
  title-block-published: "Last updated"

execute:
  freeze: auto