---
title: "Vectors and Vector Operations"
format: live-html
engine: knitr
---

We now know about the Numerics, Logicals, and Character classes; that we can use functions on these objects; and we can assign variable names to objects.

## Vectors 
A vector is a set of values of the same type. You can think of it like a column on a spreadsheet. 
We can make a vector with the `c()` function.

````{.markdown filename="practice_01.Rmd"}
```{webr}
#| autorun: false
num_vector <- c(1, 2, 3)
print (num_vector)

sus_vector <- c(1, "2", 3)
print (sus_vector)
```
````

All the elements in a vector need to be the same datatype, there are some functions that work on entire vectors. 

We can get the `mean`, or average, number of Red Bulls I drink every week for the last 6 weeks by using the `mean()` function. 

````{.markdown filename="practice_01.Rmd"}
```{webr}
#| autorun: false
redbulls_drank <- c(7, 6, 12, 8, 7, 2)
print (class(redbulls_drank))
print (mean(redbulls_drank)) 
```
````

Note that every element in `redbulls_drank` is of the numeric type. We can also do things with vectors filled with characters. The `toupper()` function turns every character into uppercase.

````{.markdown filename="practice_01.Rmd"}
```{webr}
#| autorun: false

redbull_flavor <- c("cherry", "lime", "apple", "strawberry") 
toupper(redbull_flavor)
```
````

However, it wouldn't make sense to try to get the mean of my favorite flavors. Nor would it make sense to try to uppercase numbers.

````{.markdown filename="practice_01.Rmd"}
```{webr}
#| autorun: false

print (mean(redbull_flavor)) 
print (toupper(redbulls_drank))
```
````

It also wouldn't make sense to get the mean of the number of Red Bulls I drank *and* my favorite flavors.

````{.markdown filename="practice_01.Rmd"}
```{webr}
#| autorun: false

redbull_comp <- c("cherry", "lime", "apple", "strawberry", 7, 6, 12, 8, 7, 2) 
print (mean(redbull_flavor)) 
```
````

This doesn't mean that numeric vectors can only use numeric vector functions, that logical vectors can only use logical vector functions, and so on. 
The **length()** function tells you how many elements are in a vector, and works on all kinds of vectors, and the **unique()** function tells you how many unique values are in a vector.

````{.markdown filename="practice_01.Rmd"}
```{webr}
#| autorun: false

print (length(redbull_flavor))
print (length(redbulls_drank))
print (unique(redbull_flavor))
print (unique(redbulls_drank)) 
```
````

You can also access a specific element in a vector based on its position. 
In `redbull_flavor`, "cherry" has a position of 1, "lime" has a position of 2, "apple" has a position of 3, and "strawberry" has a position of 4. We can refer to a specific element by: redbull_flavor[1], which is "cherry"

````{.markdown filename="practice_01.Rmd"}
```{webr}
#| autorun: false

print (redbull_flavor[1])
print (redbull_flavor[2])
# Same concept for redbulls_drank 
print (redbulls_drank[1])
```
````


### Vector to Vector Operations
We can work with multiple vectors. We'll make a new numeric vector that lists the number of cups of water I drank each week for the past 6 weeks.

````{.markdown filename="practice_01.Rmd"}
```{webr}
#| autorun: false
waters_drank <- c(8, 6, 9, 4, 8, 0)
```
````

We can get a new vector by adding `redbulls_drank` to `waters_drank` using the same numeric operation rules for numerics. 

````{.markdown filename="practice_01.Rmd"}
```{webr}
#| autorun: false
waters_drank + redbulls_drank 

# Subtraction
difference_vector <- waters_drank - redbulls_drank
```
````